---
version: '3.6'

services:
  dyntools-docs:
    container_name: dyntools-docs
    image: dyntools-docs:latest
    build:
      context: ..
      dockerfile: ./docsify/Dockerfile
    ports:
    - 6007:80
    restart: unless-stopped
